window.CLPQuality=(()=>{
const normalizeLabels=matrix=>{const map=new Map();let next=0;return matrix.map(row=>row.map(v=>{if(!map.has(v))map.set(v,next++);return map.get(v)}))};
function transformCoord(r,c,n,t){switch(t){case 0:return[r,c];case 1:return[c,n-1-r];case 2:return[n-1-r,n-1-c];case 3:return[n-1-c,r];case 4:return[r,n-1-c];case 5:return[n-1-r,c];case 6:return[c,r];default:return[n-1-c,n-1-r]}}
function transformed(stage,t){const n=stage.size,regions=Array.from({length:n},()=>Array(n)),cats=Array(n);for(let r=0;r<n;r++)for(let c=0;c<n;c++){const [rr,cc]=transformCoord(r,c,n,t);regions[rr][cc]=stage.regions[r][c]}for(let r=0;r<n;r++){const [rr,cc]=transformCoord(r,stage.solution[r],n,t);cats[rr]=cc}return {regions:normalizeLabels(regions),solution:cats}}
function signatureOf(x,n){return `${n}|${x.regions.map(r=>r.join(',')).join('/')}|${x.solution.join(',')}`}
function exactSignature(stage){return signatureOf({regions:normalizeLabels(stage.regions),solution:stage.solution},stage.size)}
function canonicalSignature(stage){const sigs=[];for(let t=0;t<8;t++)sigs.push(signatureOf(transformed(stage,t),stage.size));return sigs.sort()[0]}
function hash(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,'0')}
function validate(stage){const errors=[],n=stage.size;if(!Number.isInteger(n)||n<1)errors.push('盤面サイズが不正');if(!Array.isArray(stage.solution)||stage.solution.length!==n)errors.push('正解配置の長さが不正');if(!Array.isArray(stage.regions)||stage.regions.length!==n||stage.regions.some(r=>!Array.isArray(r)||r.length!==n))errors.push('色エリア配列が不正');if(errors.length)return {valid:false,errors};
 const cols=new Set(),regs=new Set();for(let r=0;r<n;r++){const c=stage.solution[r];if(!Number.isInteger(c)||c<0||c>=n){errors.push(`行${r+1}の猫位置が不正`);continue}if(cols.has(c))errors.push(`列${c+1}に猫が重複`);cols.add(c);const g=stage.regions[r][c];if(regs.has(g))errors.push(`色エリア${g}に猫が重複`);regs.add(g);if(r>0&&Math.abs(stage.solution[r-1]-c)<=1)errors.push(`行${r}と${r+1}の猫が隣接`)}
 const regionIds=new Set(stage.regions.flat());if(regionIds.size!==n)errors.push(`色エリア数が${regionIds.size}個（必要数${n}個）`);return {valid:errors.length===0,errors};
}
function countSolutions(stage,limit=2){const n=stage.size,regions=stage.regions,rows=Array.from({length:n},(_,r)=>r),regionIds=[...new Set(regions.flat())];if(regionIds.length!==n)return {count:0,nodes:0};const usedCols=new Set(),usedRegs=new Set();let count=0,nodes=0;
 function choices(r,prevCol){const out=[];for(let c=0;c<n;c++){const g=regions[r][c];if(usedCols.has(c)||usedRegs.has(g)||(prevCol!==null&&Math.abs(prevCol-c)<=1))continue;out.push(c)}return out}
 function dfs(r,prevCol){if(count>=limit)return;if(r===n){count++;return}const opts=choices(r,prevCol);for(const c of opts){nodes++;usedCols.add(c);usedRegs.add(regions[r][c]);dfs(r+1,c);usedCols.delete(c);usedRegs.delete(regions[r][c]);if(count>=limit)return}}
 dfs(0,null);return {count,nodes};
}
function inspectAll(stages){const exactSeen=new Map(),canonicalSeen=new Map(),reports=[];for(const stage of stages){const validation=validate(stage),sol=countSolutions(stage,2),exact=exactSignature(stage),canonical=canonicalSignature(stage),exactMatch=exactSeen.get(exact)||null,transformMatch=canonicalSeen.get(canonical)||null;let duplicateType='none',duplicateOf=null;if(exactMatch){duplicateType='exact';duplicateOf=exactMatch}else if(transformMatch){duplicateType='rotation-reflection';duplicateOf=transformMatch}if(!exactSeen.has(exact))exactSeen.set(exact,stage.stage);if(!canonicalSeen.has(canonical))canonicalSeen.set(canonical,stage.stage);
 let decision='accepted',reasons=[];if(!validation.valid){decision='rejected';reasons.push(...validation.errors)}if(sol.count===0){decision='rejected';reasons.push('解なし')}else if(sol.count>1){decision='rejected';reasons.push('複数解')}if(duplicateType!=='none'){decision='rejected';reasons.push(`ステージ${duplicateOf}と${duplicateType==='exact'?'完全重複':'回転・反転重複'}`)}reports.push({stage:stage.stage,size:`${stage.size}x${stage.size}`,valid:validation.valid,solutionCount:sol.count===2?'2+':sol.count,uniqueSolution:sol.count===1,nodes:sol.nodes,duplicateType,duplicateOf,fingerprint:hash(canonical),canonicalSignature:canonical,decision,reasons})}return reports}
return {validate,countSolutions,exactSignature,canonicalSignature,inspectAll};})();
